// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: garage_music

#include "ui.h"

// COMPONENT uiBtnMin1

lv_obj_t * ui_uiBtnMin1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_uiBtnMin1;
    cui_uiBtnMin1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_uiBtnMin1, 18);
    lv_obj_set_height(cui_uiBtnMin1, 17);
    lv_obj_set_align(cui_uiBtnMin1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_uiBtnMin1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_UIBTNMIN1_NUM);
    children[UI_COMP_UIBTNMIN1_UIBTNMIN1] = cui_uiBtnMin1;
    lv_obj_add_event_cb(cui_uiBtnMin1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_uiBtnMin1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_uiBtnMin1_create_hook(cui_uiBtnMin1);
    return cui_uiBtnMin1;
}



