// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: garage_music

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_imgBackground = NULL;
lv_obj_t * ui_imgAlbum = NULL;
lv_obj_t * ui_lblBtStatus = NULL;
lv_obj_t * ui_lblTitle = NULL;
lv_obj_t * ui_lblArtist = NULL;
lv_obj_t * ui_lblAlbum = NULL;
lv_obj_t * ui_barProgress = NULL;
lv_obj_t * ui_lblTimeNow = NULL;
lv_obj_t * ui_lblTimeTotal = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgBackground = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_imgBackground, &ui_img_frame_2_png);
    lv_obj_set_width(ui_imgBackground, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_imgBackground, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_imgBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgAlbum = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_imgAlbum, LV_SIZE_CONTENT);   /// 84
    lv_obj_set_height(ui_imgAlbum, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_x(ui_imgAlbum, 14);
    lv_obj_set_y(ui_imgAlbum, 42);
    lv_obj_add_flag(ui_imgAlbum, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgAlbum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblBtStatus = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblBtStatus, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_lblBtStatus, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_lblBtStatus, 214);
    lv_obj_set_y(ui_lblBtStatus, 6);
    lv_label_set_text(ui_lblBtStatus, "Wait");
    lv_obj_set_style_text_font(ui_lblBtStatus, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblBtStatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTitle = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblTitle, LV_SIZE_CONTENT);   /// 205
    lv_obj_set_height(ui_lblTitle, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_lblTitle, 106);
    lv_obj_set_y(ui_lblTitle, 42);
    lv_label_set_long_mode(ui_lblTitle, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_lblTitle, "Night Drive");
    lv_obj_set_style_text_font(ui_lblTitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblArtist = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblArtist, LV_SIZE_CONTENT);   /// 190
    lv_obj_set_height(ui_lblArtist, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_lblArtist, 122);
    lv_obj_set_y(ui_lblArtist, 73);
    lv_label_set_long_mode(ui_lblArtist, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_lblArtist, "The Midnight");
    lv_obj_set_style_text_font(ui_lblArtist, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblArtist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblAlbum = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblAlbum, LV_SIZE_CONTENT);   /// 185
    lv_obj_set_height(ui_lblAlbum, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_lblAlbum, 129);
    lv_obj_set_y(ui_lblAlbum, 103);
    lv_label_set_long_mode(ui_lblAlbum, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_lblAlbum, "Monsters");
    lv_obj_set_style_text_font(ui_lblAlbum, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblAlbum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barProgress = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_barProgress, 0, 1000);
    lv_obj_set_width(ui_barProgress, 300);
    lv_obj_set_height(ui_barProgress, 20);
    lv_obj_set_x(ui_barProgress, 10);
    lv_obj_set_y(ui_barProgress, 148);
    lv_obj_set_style_bg_color(ui_barProgress, lv_color_hex(0xF67777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTimeNow = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblTimeNow, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_lblTimeNow, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_lblTimeNow, 15);
    lv_obj_set_y(ui_lblTimeNow, 170);
    lv_label_set_text(ui_lblTimeNow, "00:00");
    lv_obj_set_style_text_font(ui_lblTimeNow, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblTimeNow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTimeTotal = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblTimeTotal, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_lblTimeTotal, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_lblTimeTotal, 254);
    lv_obj_set_y(ui_lblTimeTotal, 170);
    lv_label_set_text(ui_lblTimeTotal, "04:20");
    lv_obj_set_style_text_font(ui_lblTimeTotal, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lblTimeTotal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_imgBackground = NULL;
    ui_imgAlbum = NULL;
    ui_lblBtStatus = NULL;
    ui_lblTitle = NULL;
    ui_lblArtist = NULL;
    ui_lblAlbum = NULL;
    ui_barProgress = NULL;
    ui_lblTimeNow = NULL;
    ui_lblTimeTotal = NULL;

}


