// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: garage_music

#ifndef _UI_COMP_UIBTNMIN1_H
#define _UI_COMP_UIBTNMIN1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT uiBtnMin1
#define UI_COMP_UIBTNMIN1_UIBTNMIN1 0
#define _UI_COMP_UIBTNMIN1_NUM 1
lv_obj_t * ui_uiBtnMin1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif


