// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: garage_music

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_imgBackground;
extern lv_obj_t * ui_imgAlbum;
extern lv_obj_t * ui_lblBtStatus;
extern lv_obj_t * ui_lblTitle;
extern lv_obj_t * ui_lblArtist;
extern lv_obj_t * ui_lblAlbum;
extern lv_obj_t * ui_barProgress;
extern lv_obj_t * ui_lblTimeNow;
extern lv_obj_t * ui_lblTimeTotal;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif



